### PR TITLE
Refactor usage of deprecated `list` function

### PR DESCRIPTION
**Pull request by jverce**
* Replace calls to `list` function with new `tolist` function, as per the
  [Terraform docs](https://www.terraform.io/docs/language/functions/list.html)
* Move hardcoded `serviceAccount` values into a template YAML file

The motivation behind this change is that newer Terraform versions are throwing an exception when using this module:
```
Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to write a literal list.
```

The [Terraform docs](https://www.terraform.io/docs/language/functions/list.html) provide an alternative to use in these cases.

### CODE REVIEW

**Review by ivankatliarchuk — APPROVED** [review]
lgtm

**Comment by ivankatliarchuk** [comment]
Hello. Thanks for contribution

**Comment by ivankatliarchuk** [comment]
Ping here pls when its ready to be merged.

**Comment by jverce** [comment]
Thanks @ivankatliarchuk for the review.
I'm doing some testing on my side to verify that everything works while keeping it backwards compatible.
I'll add documentation and ping you again once it's ready for review.

Thanks again!

**Comment by jverce** [comment]
@ivankatliarchuk this change is ready now.
I took the liberty to add an extra variable called `namespace_name` which is optional and decouples the Kubernetes namespace name vs. the Helm release name and everything name-wise. It is backwards compatible, so when left unset the behaviour will be identical to the current one.

**Comment by jverce** [comment]
I forgot to run the validations and now they're passing on my side after the last commit I made ☝🏻 
However they are failing here. I'm using Linux and the Github actions are running on OSX, could that be the issue?

**Review by ivankatliarchuk — APPROVED** [review]
lgtm

**Comment by ivankatliarchuk** [comment]
I'm planning to rewrite checks. Just takes some time. Hard to say what is going on with the pre-commit, probably some tooling is not installed

**Pull request merged**
